### ISSUE TITLE
syntax error when trying to import this in my webpack config

### ISSUE THREAD

**Issue by radix** [ch1ffa/relay-compiler-webpack-plugin#1]
Hi, maybe this code requires some newer version of node or something (I'm still on Node 10), but I can't use this plugin when I used to be able to use the old plugin.

```
/code/node_modules/@ch1ffa/relay-compiler-webpack-plugin/dist/index.js:47
  subprocess;
            ^

SyntaxError: Unexpected token ;
```

Does this require a newer version of Node or something? I've never seen that syntax.

**Comment by ch1ffa** [comment]
Hi @radix! 

Thank you for your report! I didn't test it with older node versions. Let me check what I can do.

**Comment by radix** [comment]
@ch1ffa well, now that I know it's just a node incompatibility issue, I solved the problem by upgrading from node 10 to node 16 :)

**Comment by ch1ffa** [comment]
@radix good! Anyway, I changed tsconfig a bit. Now it should work with node >= 12.
